[package]
name = "me"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
yew-hooks = "0.3"
yew-router = "0.18"
wasm-bindgen = "0.2"
